version: "3"

services:
  goolang-api-service:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - redis-db
  redis-db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .redis-data:/data